"""Add place_image table

Revision ID: 950769eeac1b
Revises: 48acf29ec26a
Create Date: 2024-01-02 18:13:59.148796

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "950769eeac1b"
down_revision = "48acf29ec26a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place_image",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_place_image_place_id"), "place_image", ["place_id"], unique=False
    )
    op.create_index(op.f("ix_place_image_url"), "place_image", ["url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_place_image_url"), table_name="place_image")
    op.drop_index(op.f("ix_place_image_place_id"), table_name="place_image")
    op.drop_table("place_image")
    # ### end Alembic commands ###
