"""Change time_open and time_close

Revision ID: 48acf29ec26a
Revises: 4d9668dd73a5
Create Date: 2024-01-02 17:48:08.315699

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "48acf29ec26a"
down_revision = "4d9668dd73a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "place",
        "time_open",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Time(),
        existing_nullable=False,
    )
    op.alter_column(
        "place",
        "time_close",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Time(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "place",
        "time_close",
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "place",
        "time_open",
        existing_type=sa.Time(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
