"""Rename singular tables into plural tables

Revision ID: f3225a6a04c4
Revises: 910dda330545
Create Date: 2024-01-04 16:18:41.979692

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f3225a6a04c4"
down_revision = "910dda330545"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE city RENAME TO cities")
    op.execute("ALTER TABLE district RENAME TO districts")
    op.execute("ALTER TABLE place RENAME TO places")
    op.execute("ALTER TABLE place_type RENAME TO place_types")
    op.execute("ALTER TABLE \"user\" RENAME TO users")
    op.drop_index("ix_place_image_place_id", table_name="place_images")
    op.drop_index("ix_place_image_url", table_name="place_images")
    op.create_index(
        op.f("ix_place_images_place_id"), "place_images", ["place_id"], unique=False
    )
    op.create_index(op.f("ix_place_images_url"), "place_images", ["url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_place_images_url"), table_name="place_images")
    op.drop_index(op.f("ix_place_images_place_id"), table_name="place_images")
    op.create_index("ix_place_image_url", "place_images", ["url"], unique=False)
    op.create_index(
        "ix_place_image_place_id", "place_images", ["place_id"], unique=False
    )
    op.execute("ALTER TABLE users RENAME TO \"user\"")
    op.execute("ALTER TABLE place_types RENAME TO place_type")
    op.execute("ALTER TABLE places RENAME TO place")
    op.execute("ALTER TABLE districts RENAME TO district")
    op.execute("ALTER TABLE cities RENAME TO city")
    # ### end Alembic commands ###
