"""Change name of type_id

Revision ID: 74dd70fb6186
Revises: f153160c9e8a
Create Date: 2024-01-04 21:55:00.143504

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74dd70fb6186"
down_revision = "f153160c9e8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("places", sa.Column("place_type_id", sa.Integer(), nullable=False))
    op.drop_constraint("card_type_id_fkey", "places", type_="foreignkey")
    op.create_foreign_key(None, "places", "place_types", ["place_type_id"], ["id"])
    op.drop_column("places", "type_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "places",
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "places", type_="foreignkey")
    op.create_foreign_key(
        "card_type_id_fkey", "places", "place_types", ["type_id"], ["id"]
    )
    op.drop_column("places", "place_type_id")
    # ### end Alembic commands ###
