"""Rename column place_images and foreign keys

Revision ID: f153160c9e8a
Revises: f3225a6a04c4
Create Date: 2024-01-04 21:40:36.259648

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f153160c9e8a"
down_revision = "f3225a6a04c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_city_alias", table_name="cities")
    op.drop_index("ix_city_name", table_name="cities")
    op.create_index(op.f("ix_cities_alias"), "cities", ["alias"], unique=False)
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    op.drop_index("ix_district_alias", table_name="districts")
    op.drop_index("ix_district_name", table_name="districts")
    op.create_index(op.f("ix_districts_alias"), "districts", ["alias"], unique=False)
    op.create_index(op.f("ix_districts_name"), "districts", ["name"], unique=False)
    op.add_column(
        "place_images", sa.Column("path", sa.String(length=255), nullable=False)
    )
    op.drop_index("ix_place_images_url", table_name="place_images")
    op.create_index(
        op.f("ix_place_images_path"), "place_images", ["path"], unique=False
    )
    op.drop_column("place_images", "url")
    op.drop_index("ix_place_type_alias", table_name="place_types")
    op.drop_index("ix_place_type_name", table_name="place_types")
    op.create_index(
        op.f("ix_place_types_alias"), "place_types", ["alias"], unique=False
    )
    op.create_index(op.f("ix_place_types_name"), "place_types", ["name"], unique=False)
    op.drop_index("ix_place_alias", table_name="places")
    op.drop_index("ix_place_name", table_name="places")
    op.create_index(op.f("ix_places_alias"), "places", ["alias"], unique=False)
    op.create_index(op.f("ix_places_name"), "places", ["name"], unique=False)
    op.drop_index("ix_user_email", table_name="users")
    op.drop_index("ix_user_username", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_user_username", "users", ["username"], unique=False)
    op.create_index("ix_user_email", "users", ["email"], unique=False)
    op.drop_index(op.f("ix_places_name"), table_name="places")
    op.drop_index(op.f("ix_places_alias"), table_name="places")
    op.create_index("ix_place_name", "places", ["name"], unique=False)
    op.create_index("ix_place_alias", "places", ["alias"], unique=False)
    op.drop_index(op.f("ix_place_types_name"), table_name="place_types")
    op.drop_index(op.f("ix_place_types_alias"), table_name="place_types")
    op.create_index("ix_place_type_name", "place_types", ["name"], unique=False)
    op.create_index("ix_place_type_alias", "place_types", ["alias"], unique=False)
    op.add_column(
        "place_images",
        sa.Column("url", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_place_images_path"), table_name="place_images")
    op.create_index("ix_place_images_url", "place_images", ["url"], unique=False)
    op.drop_column("place_images", "path")
    op.drop_index(op.f("ix_districts_name"), table_name="districts")
    op.drop_index(op.f("ix_districts_alias"), table_name="districts")
    op.create_index("ix_district_name", "districts", ["name"], unique=False)
    op.create_index("ix_district_alias", "districts", ["alias"], unique=False)
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_index(op.f("ix_cities_alias"), table_name="cities")
    op.create_index("ix_city_name", "cities", ["name"], unique=False)
    op.create_index("ix_city_alias", "cities", ["alias"], unique=False)
    # ### end Alembic commands ###
