"""New tables liked and viewd places

Revision ID: 4d9668dd73a5
Revises: 2eec8cbdff33
Create Date: 2024-01-02 16:52:36.296238

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d9668dd73a5"
down_revision = "2eec8cbdff33"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "liked_places",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_liked_places_place_id"), "liked_places", ["place_id"], unique=False
    )
    op.create_index(
        op.f("ix_liked_places_user_id"), "liked_places", ["user_id"], unique=False
    )
    op.create_table(
        "viewed_places",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column("date_last_viewed", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_viewed_places_place_id"), "viewed_places", ["place_id"], unique=False
    )
    op.create_index(
        op.f("ix_viewed_places_user_id"), "viewed_places", ["user_id"], unique=False
    )
    op.add_column("place", sa.Column("rating", sa.Float(), nullable=False))
    op.add_column("place", sa.Column("views_amount", sa.Integer(), nullable=False))
    op.add_column("place", sa.Column("liked_amount", sa.Integer(), nullable=False))
    op.drop_index("ix_card_alias", table_name="place")
    op.drop_index("ix_card_name", table_name="place")
    op.create_index(op.f("ix_place_alias"), "place", ["alias"], unique=False)
    op.create_index(op.f("ix_place_name"), "place", ["name"], unique=False)
    op.drop_column("place", "total_rating")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "place",
        sa.Column(
            "total_rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_place_name"), table_name="place")
    op.drop_index(op.f("ix_place_alias"), table_name="place")
    op.create_index("ix_card_name", "place", ["name"], unique=False)
    op.create_index("ix_card_alias", "place", ["alias"], unique=False)
    op.drop_column("place", "liked_amount")
    op.drop_column("place", "views_amount")
    op.drop_column("place", "rating")
    op.drop_index(op.f("ix_viewed_places_user_id"), table_name="viewed_places")
    op.drop_index(op.f("ix_viewed_places_place_id"), table_name="viewed_places")
    op.drop_table("viewed_places")
    op.drop_index(op.f("ix_liked_places_user_id"), table_name="liked_places")
    op.drop_index(op.f("ix_liked_places_place_id"), table_name="liked_places")
    op.drop_table("liked_places")
    # ### end Alembic commands ###
