"""Rename table place

Revision ID: 2eec8cbdff33
Revises: 9723e55d7ee3
Create Date: 2024-01-02 16:34:56.475091

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2eec8cbdff33"
down_revision = "9723e55d7ee3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE card RENAME TO place")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE place RENAME TO card")
    # ### end Alembic commands ###
