"""Rename place_image table

Revision ID: 910dda330545
Revises: 950769eeac1b
Create Date: 2024-01-02 18:14:28.308010

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "910dda330545"
down_revision = "950769eeac1b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE place_image RENAME TO place_images")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE place_images RENAME TO place_image")
    # ### end Alembic commands ###
